### ISSUE TITLE
Delay necessary

### ISSUE THREAD

**Issue by smamessier** [cotag/a2-file-drop#1]
I got the dropTarget directive to work with the following usage modification

* Use `<div dropTarget></div>` instead of `<div drop-target></div>`

* Add a delay in the observable sequence:
```typescript
    this.fileStream.filter(e => e.event == 'drop')
                    .delay(10)
                    .flatMap(e => this.stringFromFile(e.data.files[0])
```

For some obscure reason, without the delay, the files array is empty when the event cascades.

**Comment by stakach** [comment]
Thanks for pointing out the `dropTarget` issue.
In terms of the delay, it isn't required and is just a side effect of what is going on in the background.

You should find the delay isn't required on browsers other than chrome and opera. This is because we track the directory structure in those browsers - the side effect of which it takes a little longer to obtain the file list.

I based this off the example in the readme and added some annotations

```typescript
stream.filter((obj) => {
    // Files only available on a drop event (filter for drop event - faster than string compare)
    return obj.data && obj.data.length > 0;
}).flatMap((obj) => {
    // Wait for the files to be collected (this promise ensures the file list is built)
    return obj.data.promise;
}).map((obj) => {
    // Return just the array of files (this returns just the array of files)
    return obj.files;
}).flatMap((files) => {
    this.stringFromFile(files[0]);
}).subscribe((fileString) => {
    console.log(fileString);
});
```

**Comment by smamessier** [comment]
My bad, I didn't read carefully and missed the part where you get the promise. Anyhow, thanks for the good work, this project was very useful to me!
